"""AI-assisted, fictional civic scenarios. These are authored fixtures, not citizen reports."""

# Each severity has its own description; emergency labels are never assigned to routine text.
# Tuples contain aligned English, Tamil and Telugu versions of the same request.
SCENARIOS = {
    'Water Supply': {
        'Routine': ('Our street gets water only on alternate days. Please add storage and repair the distribution line so every household has a reliable supply.', 'எங்கள் தெருவில் ஒரு நாள் விட்டு ஒரு நாள்தான் தண்ணீர் வருகிறது. எல்லா வீடுகளுக்கும் சீராக குடிநீர் கிடைக்க கூடுதல் சேமிப்புத் தொட்டியும் பழைய குழாய் சீரமைப்பும் தேவை.', 'మా వీధిలో రోజు విడిచి రోజు మాత్రమే నీళ్లు వస్తున్నాయి. ప్రతి ఇంటికి క్రమంగా తాగునీరు అందేలా అదనపు నిల్వ ట్యాంకు ఏర్పాటు చేసి పాత పైపులైనును బాగుచేయండి.'),
        'Urgent': ('The drinking-water line has been dry for three days. Families are buying water. Please arrange temporary supply and repair the failed pump.', 'மூன்று நாட்களாக குடிநீர் குழாயில் தண்ணீர் வரவில்லை. குடும்பங்கள் தண்ணீரை விலைக்கு வாங்குகின்றன. தற்காலிக குடிநீர் வழங்கி பழுதான பம்பை சரிசெய்யுங்கள்.', 'మూడు రోజులుగా తాగునీటి పైపులో నీళ్లు రావడం లేదు. కుటుంబాలు నీటిని కొనుక్కుంటున్నాయి. తాత్కాలిక నీటి సరఫరా ఏర్పాటు చేసి పాడైన పంపును బాగుచేయండి.'),
        'Emergency': ('Sewage has entered the drinking-water line and children are falling ill. Please stop the unsafe supply, provide safe water and send a health inspection team immediately.', 'குடிநீர் குழாயில் கழிவுநீர் கலந்து குழந்தைகளுக்கு உடல்நலக் குறைவு ஏற்பட்டுள்ளது. பாதுகாப்பற்ற விநியோகத்தை நிறுத்தி சுத்தமான குடிநீர் வழங்கவும்; சுகாதாரக் குழுவை உடனே அனுப்பவும்.', 'తాగునీటి పైపులో మురుగునీరు కలిసి పిల్లలు అస్వస్థతకు గురవుతున్నారు. కలుషిత సరఫరాను నిలిపి సురక్షిత నీరు అందించండి. వెంటనే ఆరోగ్య తనిఖీ బృందాన్ని పంపండి.'),
    },
    'Road': {
        'Routine': ('The unpaved approach road becomes muddy during rain. Please build an all-weather road with side drains for school trips and transport to the market.', 'மழை பெய்தால் எங்கள் பகுதியின் மண் சாலை சேறும் சகதியுமாகிறது. பள்ளிக்கும் சந்தைக்கும் செல்ல பக்கவாட்டு வடிகாலுடன் அனைத்து காலநிலைக்கும் ஏற்ற சாலை அமைக்க வேண்டும்.', 'వర్షం పడితే మా ప్రాంతానికి వచ్చే మట్టి రోడ్డు బురదగా మారుతోంది. పాఠశాలకూ మార్కెట్‌కూ వెళ్లేందుకు పక్క కాలువలతో అన్ని కాలాల్లో ఉపయోగపడే రోడ్డు వేయండి.'),
        'Urgent': ('Deep potholes have damaged the school-bus route. Two-wheelers skid after rain. Please repair this stretch and mark the damaged sections until work is complete.', 'பள்ளிப் பேருந்து செல்லும் சாலையில் ஆழமான பள்ளங்கள் உள்ளன. மழைக்குப் பிறகு இருசக்கர வாகனங்கள் வழுக்குகின்றன. சாலையை சீரமைத்து அதுவரை ஆபத்தான இடங்களில் எச்சரிக்கை அமைக்கவும்.', 'పాఠశాల బస్సు వెళ్లే రోడ్డులో లోతైన గుంతలు ఉన్నాయి. వర్షం తరువాత ద్విచక్ర వాహనాలు జారిపోతున్నాయి. రోడ్డును బాగుచేసి అప్పటివరకు ప్రమాద ప్రాంతాల్లో హెచ్చరికలు పెట్టండి.'),
        'Emergency': ('The culvert has collapsed and vehicles are approaching the broken edge. The ambulance route is cut off. Please barricade the site and arrange safe access immediately.', 'சிறுபாலம் இடிந்து விழுந்துள்ளது; உடைந்த விளிம்பை நோக்கி வாகனங்கள் வருகின்றன. ஆம்புலன்ஸ் செல்லும் வழியும் துண்டிக்கப்பட்டுள்ளது. உடனே தடுப்பு அமைத்து பாதுகாப்பான மாற்றுப் பாதை ஏற்பாடு செய்யவும்.', 'చిన్న వంతెన కూలిపోయింది; వాహనాలు విరిగిన అంచు వైపు వస్తున్నాయి. అంబులెన్స్ దారి కూడా మూసుకుపోయింది. వెంటనే అడ్డుకట్టలు పెట్టి సురక్షిత ప్రత్యామ్నాయ దారి ఏర్పాటు చేయండి.'),
    },
    'Sanitation': {
        'Routine': ('There is no covered drain or regular waste collection on our street. Please plan drainage and a segregated waste collection point before the next rainy season.', 'எங்கள் தெருவில் மூடிய வடிகாலும் முறையான குப்பை சேகரிப்பும் இல்லை. அடுத்த மழைக்காலத்திற்கு முன் வடிகாலும் பிரித்த குப்பை சேகரிக்கும் இடமும் அமைக்க வேண்டும்.', 'మా వీధిలో మూసిన కాలువ లేదు; క్రమంగా చెత్త సేకరణ కూడా జరగడం లేదు. వచ్చే వర్షాకాలానికి ముందు కాలువ, వేరు చేసిన చెత్త సేకరణ కేంద్రం ఏర్పాటు చేయండి.'),
        'Urgent': ('The drain has been blocked for a week and stagnant water surrounds the homes. Please clear it and replace the broken section to prevent repeated blockages.', 'ஒரு வாரமாக வடிகால் அடைந்து வீடுகளைச் சுற்றி தண்ணீர் தேங்கியுள்ளது. அடைப்பை அகற்றி மீண்டும் அடையாமல் உடைந்த பகுதியை மாற்ற வேண்டும்.', 'వారం రోజులుగా కాలువ మూసుకుపోయి ఇళ్ల చుట్టూ నీరు నిలిచింది. అడ్డంకిని తొలగించి మళ్లీ సమస్య రాకుండా విరిగిన భాగాన్ని మార్చండి.'),
        'Emergency': ('An overflowing sewer is flooding the school entrance with sewage. Children cannot enter safely. Please isolate the area and send an emergency sanitation team.', 'பள்ளி நுழைவாயிலில் பாதாள சாக்கடை பொங்கி கழிவுநீர் வெள்ளமாக ஓடுகிறது. குழந்தைகள் பாதுகாப்பாக உள்ளே செல்ல முடியவில்லை. பகுதியை தனிமைப்படுத்தி அவசர சுகாதாரக் குழுவை அனுப்பவும்.', 'పాఠశాల ప్రవేశద్వారం వద్ద మురుగు పొంగి ప్రవహిస్తోంది. పిల్లలు సురక్షితంగా లోపలికి వెళ్లలేకపోతున్నారు. ప్రాంతాన్ని మూసివేసి అత్యవసర పారిశుధ్య బృందాన్ని పంపండి.'),
    },
    'Electricity': {
        'Routine': ('Several lanes have no working streetlights and the transformer is overloaded in the evening. Please include lighting and feeder upgrades in the local infrastructure plan.', 'பல தெருக்களில் தெருவிளக்குகள் இயங்கவில்லை; மாலையில் மின்மாற்றியில் அதிக சுமை ஏற்படுகிறது. உள்ளூர் கட்டமைப்புத் திட்டத்தில் விளக்குகள் மற்றும் மின்பாதை மேம்பாட்டை சேர்க்க வேண்டும்.', 'కొన్ని వీధుల్లో వీధి దీపాలు పనిచేయడం లేదు; సాయంత్రం ట్రాన్స్‌ఫార్మర్‌పై అధిక భారం పడుతోంది. స్థానిక మౌలిక వసతుల ప్రణాళికలో దీపాలు, విద్యుత్ లైన్ మెరుగుదల చేర్చండి.'),
        'Urgent': ('Repeated feeder failures interrupt the water pump and small shops every evening. Please inspect the transformer and repair the weak distribution line.', 'மின்பாதை அடிக்கடி பழுதாவதால் தினமும் மாலையில் குடிநீர் பம்பும் சிறு கடைகளும் பாதிக்கப்படுகின்றன. மின்மாற்றியை ஆய்வு செய்து பலவீனமான மின்பாதையை சரிசெய்யவும்.', 'పదేపదే విద్యుత్ లైన్ దెబ్బతినడంతో సాయంత్రం నీటి పంపు, చిన్న దుకాణాలు ఆగిపోతున్నాయి. ట్రాన్స్‌ఫార్మర్‌ను తనిఖీ చేసి బలహీనమైన లైనును బాగుచేయండి.'),
        'Emergency': ('A live electricity wire has fallen into standing water near the bus stop. People are still walking past it. Please disconnect the supply and secure the area immediately.', 'பேருந்து நிறுத்தம் அருகே தேங்கிய நீரில் மின்சாரம் பாயும் கம்பி அறுந்து விழுந்துள்ளது. மக்கள் அதன் அருகே நடந்து செல்கின்றனர். உடனே மின்சாரத்தை துண்டித்து பகுதியை பாதுகாக்கவும்.', 'బస్సు నిలయం దగ్గర నిలిచిన నీటిలో విద్యుత్ తీగ తెగిపడింది. ప్రజలు దాని పక్కనే నడుస్తున్నారు. వెంటనే విద్యుత్ నిలిపి ప్రాంతాన్ని సురక్షితం చేయండి.'),
    },
    'Health': {
        'Routine': ('The health sub-centre has no reliable power backup or vaccine cold storage. Please upgrade the building and equipment so antenatal visits and immunisation can run regularly.', 'துணை சுகாதார நிலையத்தில் நம்பகமான மாற்று மின்சாரமும் தடுப்பூசி குளிர்சாதன வசதியும் இல்லை. கர்ப்பகால பரிசோதனையும் தடுப்பூசி பணியும் தொடர்ந்து நடைபெற கட்டடத்தையும் சாதனங்களையும் மேம்படுத்த வேண்டும்.', 'ఆరోగ్య ఉపకేంద్రంలో నమ్మకమైన విద్యుత్ బ్యాకప్, టీకాల శీతల నిల్వ లేవు. గర్భిణుల పరీక్షలు, టీకాలు క్రమంగా జరిగేలా భవనం, పరికరాలను మెరుగుపరచండి.'),
        'Urgent': ('The primary health centre has no doctor on several clinic days. Patients travel far for basic care. Please arrange a visiting team and improve the referral transport link.', 'ஆரம்ப சுகாதார நிலையத்தில் பல மருத்துவ நாட்களில் மருத்துவர் இல்லை. அடிப்படை சிகிச்சைக்கே நோயாளிகள் தொலைவு செல்கின்றனர். வருகை மருத்துவக் குழுவையும் பரிந்துரை போக்குவரத்து வசதியையும் ஏற்பாடு செய்யவும்.', 'ప్రాథమిక ఆరోగ్య కేంద్రంలో కొన్ని వైద్య సేవల రోజుల్లో డాక్టర్ ఉండటం లేదు. సాధారణ చికిత్సకే రోగులు దూరం వెళ్లాలి. సందర్శక వైద్య బృందం, రిఫరల్ రవాణా ఏర్పాటు చేయండి.'),
        'Emergency': ('The health centre has lost power and its oxygen equipment has stopped while patients need care. Please send emergency medical support and restore backup power now.', 'நோயாளிகளுக்கு சிகிச்சை தேவைப்படும் நேரத்தில் சுகாதார நிலையத்தில் மின்சாரம் துண்டிக்கப்பட்டு ஆக்சிஜன் சாதனம் நின்றுள்ளது. அவசர மருத்துவ உதவி அனுப்பி மாற்று மின்சாரத்தை உடனே மீட்டெடுக்கவும்.', 'రోగులకు చికిత్స అవసరమైన సమయంలో ఆరోగ్య కేంద్రంలో విద్యుత్ పోయి ఆక్సిజన్ పరికరం ఆగిపోయింది. వెంటనే అత్యవసర వైద్య సహాయం పంపి బ్యాకప్ విద్యుత్ పునరుద్ధరించండి.'),
    },
    'Education': {
        'Routine': ('The government school needs an additional classroom, accessible toilets and drinking-water storage. Please include these together in the school infrastructure plan.', 'அரசுப் பள்ளிக்கு கூடுதல் வகுப்பறை, மாற்றுத்திறனாளிகள் பயன்படுத்தும் கழிப்பறை மற்றும் குடிநீர் சேமிப்பு தேவை. இவற்றை ஒருங்கிணைத்து பள்ளிக் கட்டமைப்புத் திட்டத்தில் சேர்க்கவும்.', 'ప్రభుత్వ పాఠశాలకు అదనపు తరగతి గది, దివ్యాంగులకు అనుకూల మరుగుదొడ్లు, తాగునీటి నిల్వ అవసరం. వీటిని కలిపి పాఠశాల మౌలిక వసతుల ప్రణాళికలో చేర్చండి.'),
        'Urgent': ('School toilets are unusable and the water tank is broken. Children are missing classes. Please restore water and sanitation before the next school week.', 'பள்ளிக் கழிப்பறைகளை பயன்படுத்த முடியவில்லை; தண்ணீர் தொட்டியும் உடைந்துள்ளது. குழந்தைகள் வகுப்புகளுக்கு வராமல் உள்ளனர். அடுத்த பள்ளி வாரத்திற்கு முன் குடிநீரையும் கழிப்பறைகளையும் சீரமைக்கவும்.', 'పాఠశాల మరుగుదొడ్లు ఉపయోగించలేని స్థితిలో ఉన్నాయి; నీటి ట్యాంకు పాడైంది. పిల్లలు తరగతులు కోల్పోతున్నారు. వచ్చే పాఠశాల వారానికి ముందు నీరు, మరుగుదొడ్లు పునరుద్ధరించండి.'),
        'Emergency': ('Pieces of the classroom roof are falling and a large crack is visible. Children are still using the room. Please relocate classes and inspect the building immediately.', 'வகுப்பறை கூரையிலிருந்து துண்டுகள் விழுகின்றன; பெரிய விரிசலும் தெரிகிறது. குழந்தைகள் இன்னும் அந்த அறையை பயன்படுத்துகின்றனர். வகுப்புகளை மாற்றி கட்டடத்தை உடனே ஆய்வு செய்யவும்.', 'తరగతి గది పైకప్పు ముక్కలు పడుతున్నాయి; పెద్ద పగులు కనిపిస్తోంది. పిల్లలు ఇంకా ఆ గదినే వాడుతున్నారు. తరగతులను మార్చి భవనాన్ని వెంటనే తనిఖీ చేయండి.'),
    },
    'Transport': {
        'Routine': ('Our settlement needs a covered, accessible bus stop and a regular route to the market and health centre. Please plan the stop and service together.', 'எங்கள் குடியிருப்பிற்கு நிழற்குடையுடன் அணுகக்கூடிய பேருந்து நிறுத்தமும் சந்தை மற்றும் சுகாதார நிலையத்திற்கு முறையான பேருந்து சேவையும் தேவை. நிறுத்தத்தையும் சேவையையும் இணைந்து திட்டமிடவும்.', 'మా నివాస ప్రాంతానికి అందరికీ అనుకూలమైన కప్పుతో కూడిన బస్సు నిలయం, మార్కెట్‌కు ఆరోగ్య కేంద్రానికి క్రమమైన బస్సు అవసరం. నిలయాన్ని, సేవను కలిపి ప్రణాళిక చేయండి.'),
        'Urgent': ('The morning bus has stopped serving our route. Students and workers are missing school and work. Please restore the trip and publish a dependable timetable.', 'எங்கள் வழித்தடத்தில் காலை பேருந்து வருவதில்லை. மாணவர்களும் தொழிலாளர்களும் பள்ளிக்கும் வேலைக்கும் செல்ல முடியவில்லை. சேவையை மீட்டெடுத்து நம்பகமான நேர அட்டவணையை வெளியிடவும்.', 'మా మార్గంలో ఉదయం బస్సు రావడం లేదు. విద్యార్థులు, కార్మికులు పాఠశాలకు పనికి వెళ్లలేకపోతున్నారు. ట్రిప్ పునరుద్ధరించి నమ్మకమైన సమయ పట్టిక ప్రకటించండి.'),
        'Emergency': ('The bus-stop shelter is partly collapsed and a loose beam hangs over waiting passengers. Please close the shelter and provide a safe temporary boarding point.', 'பேருந்து நிறுத்த நிழற்குடை ஒரு பகுதி இடிந்து பயணிகள் மீது தளர்ந்த தூண் தொங்குகிறது. நிழற்குடையை மூடி பாதுகாப்பான தற்காலிக பேருந்து ஏறும் இடம் அமைக்கவும்.', 'బస్సు నిలయం కప్పు కొంత కూలి వేచి ఉన్న ప్రయాణికులపై వదులైన దూలం వేలాడుతోంది. నిలయాన్ని మూసి సురక్షిత తాత్కాలిక ఎక్కే ప్రదేశం ఏర్పాటు చేయండి.'),
    },
    'Housing': {
        'Routine': ('Families in temporary houses need weatherproof homes with water, toilets and a safe approach path. Please assess eligibility and plan basic services with the housing work.', 'தற்காலிக வீடுகளில் உள்ள குடும்பங்களுக்கு குடிநீர், கழிப்பறை, பாதுகாப்பான பாதையுடன் மழையைத் தாங்கும் வீடுகள் தேவை. தகுதியை மதிப்பிட்டு வீடுகளுடன் அடிப்படை வசதிகளையும் திட்டமிடவும்.', 'తాత్కాలిక ఇళ్లలో ఉన్న కుటుంబాలకు నీరు, మరుగుదొడ్లు, సురక్షిత దారితో వర్షాన్ని తట్టుకునే ఇళ్లు కావాలి. అర్హత పరిశీలించి ఇళ్లతో పాటు ప్రాథమిక సేవలను ప్రణాళిక చేయండి.'),
        'Urgent': ('Rain is entering damaged houses and families cannot keep bedding dry. Please arrange temporary protection and inspect the homes for repair assistance.', 'பழுதான வீடுகளுக்குள் மழைநீர் புகுவதால் குடும்பங்கள் படுக்கைகளைக்கூட உலர வைக்க முடியவில்லை. தற்காலிக பாதுகாப்பு அளித்து பழுதுபார்ப்பு உதவிக்காக வீடுகளை ஆய்வு செய்யவும்.', 'పాడైన ఇళ్లలోకి వర్షం వచ్చి కుటుంబాలు పరుపులను కూడా పొడిగా ఉంచలేకపోతున్నాయి. తాత్కాలిక రక్షణ కల్పించి మరమ్మతు సహాయం కోసం ఇళ్లను పరిశీలించండి.'),
        'Emergency': ('The retaining wall above occupied houses is leaning and fresh cracks have appeared after rain. Please evacuate people at risk and send a structural safety team immediately.', 'மக்கள் வசிக்கும் வீடுகளுக்கு மேலுள்ள தடுப்புச்சுவர் சாய்ந்து மழைக்குப் பிறகு புதிய விரிசல்கள் ஏற்பட்டுள்ளன. ஆபத்தில் உள்ளவர்களை வெளியேற்றி கட்டமைப்பு பாதுகாப்புக் குழுவை உடனே அனுப்பவும்.', 'ప్రజలు నివసించే ఇళ్ల పైన ఉన్న రక్షణ గోడ ఒరిగి వర్షం తరువాత కొత్త పగుళ్లు వచ్చాయి. ప్రమాదంలో ఉన్నవారిని తరలించి నిర్మాణ భద్రత బృందాన్ని వెంటనే పంపండి.'),
    },
    'Digital Connectivity': {
        'Routine': ('The village service centre and school need reliable broadband. Please extend the fibre link and provide backup power so residents can access public digital services locally.', 'கிராம சேவை மையத்திற்கும் பள்ளிக்கும் நம்பகமான இணைய இணைப்பு தேவை. மக்கள் உள்ளூரிலேயே அரசு இணைய சேவைகளைப் பெற கண்ணாடி இழை இணைப்பையும் மாற்று மின்சாரத்தையும் ஏற்பாடு செய்யவும்.', 'గ్రామ సేవా కేంద్రం, పాఠశాలకు నమ్మకమైన బ్రాడ్‌బ్యాండ్ కావాలి. ప్రజలు స్థానికంగా ప్రభుత్వ డిజిటల్ సేవలు పొందేలా ఫైబర్ లింకు, బ్యాకప్ విద్యుత్ ఏర్పాటు చేయండి.'),
        'Urgent': ('The service centre internet has failed repeatedly during benefit applications. Residents make repeated trips. Please repair the link and arrange a backup connection.', 'நலத்திட்ட விண்ணப்பங்களின்போது சேவை மைய இணையம் அடிக்கடி செயலிழக்கிறது. மக்கள் மீண்டும் மீண்டும் வர வேண்டியுள்ளது. இணைப்பை சரிசெய்து மாற்று இணைப்பும் ஏற்பாடு செய்யவும்.', 'పథకాల దరఖాస్తుల సమయంలో సేవా కేంద్రం ఇంటర్నెట్ పదేపదే ఆగిపోతోంది. ప్రజలు మళ్లీ మళ్లీ రావాలి. లింకును బాగుచేసి ప్రత్యామ్నాయ కనెక్షన్ ఏర్పాటు చేయండి.'),
        'Emergency': ('The rural clinic has lost both its phone and data connection during an emergency referral. Please provide an immediate communication link and repair the failed network.', 'அவசர பரிந்துரை சிகிச்சையின்போது கிராம மருத்துவ நிலையத்தின் தொலைபேசியும் இணையமும் துண்டிக்கப்பட்டுள்ளன. உடனடி தொடர்பு வசதி அளித்து பழுதான வலையமைப்பை சீரமைக்கவும்.', 'అత్యవసర రిఫరల్ సమయంలో గ్రామ క్లినిక్ ఫోన్, డేటా కనెక్షన్ రెండూ పోయాయి. వెంటనే సమాచార సంబంధం కల్పించి పాడైన నెట్‌వర్క్‌ను బాగుచేయండి.'),
    },
    'Other': {
        'Routine': ('The community service building has no accessible entrance or rainwater storage. Please upgrade it as a shared service point and temporary shelter during severe weather.', 'சமுதாய சேவைக் கட்டடத்தில் அணுகக்கூடிய நுழைவாயிலும் மழைநீர் சேமிப்பும் இல்லை. பொதுச் சேவை மையமாகவும் கடுமையான வானிலையில் தற்காலிக தங்குமிடமாகவும் மேம்படுத்தவும்.', 'సామాజిక సేవా భవనంలో అందరికీ అనుకూల ప్రవేశం, వర్షపు నీటి నిల్వ లేవు. ఉమ్మడి సేవా కేంద్రంగా, తీవ్ర వాతావరణంలో తాత్కాలిక ఆశ్రయంగా మెరుగుపరచండి.'),
        'Urgent': ('Water is collecting inside the public market because its drainage is damaged. Small vendors are losing goods. Please clear the water and repair the market drains.', 'பொதுச் சந்தையின் வடிகால் பழுதாகி உள்ளே தண்ணீர் தேங்குகிறது. சிறு வியாபாரிகளின் பொருட்கள் சேதமடைகின்றன. நீரை அகற்றி சந்தை வடிகால்களை சரிசெய்யவும்.', 'ప్రజా మార్కెట్ కాలువలు పాడై లోపల నీరు నిలుస్తోంది. చిన్న వ్యాపారుల సరుకులు నష్టపోతున్నాయి. నీటిని తొలగించి మార్కెట్ కాలువలను బాగుచేయండి.'),
        'Emergency': ('The village pond bund has breached and water is flowing toward homes. Please warn residents, move people to safety and send the emergency public-works team.', 'கிராமக் குளத்தின் கரை உடைந்து வீடுகளை நோக்கி தண்ணீர் பாய்கிறது. மக்களை எச்சரித்து பாதுகாப்பான இடத்திற்கு மாற்றி அவசர பொதுப்பணிக் குழுவை அனுப்பவும்.', 'గ్రామ చెరువు కట్ట తెగి ఇళ్ల వైపు నీరు వస్తోంది. ప్రజలను హెచ్చరించి సురక్షిత ప్రదేశానికి తరలించి అత్యవసర ప్రజాపనుల బృందాన్ని పంపండి.'),
    },
}

PROJECT_RESPONSES = {
    'Water Supply': ('Reliable piped-water network, storage and source protection', ['Jal Jeevan Mission / AMRUT 2.0, subject to rural/urban eligibility', 'MGNREGA for eligible source-protection works', 'Local-body finance for maintenance']),
    'Road': ('All-weather access road with drainage and a safe culvert', ['PMGSY for eligible rural connectivity', 'State roads programme', 'Local-body drainage budget']),
    'Sanitation': ('Connected stormwater drainage and safe waste management', ['Swachh Bharat Mission 2.0', 'AMRUT 2.0 where eligible', 'Local-body maintenance budget']),
    'Electricity': ('Safer distribution feeder and resilient public-service power', ['RDSS subject to utility eligibility', 'State distribution-utility capital plan']),
    'Health': ('Accessible primary care with reliable power and referral access', ['National Health Mission', 'PM-ABHIM where eligible', 'State health capital plan']),
    'Education': ('Safe and inclusive school with water, toilets and classrooms', ['Samagra Shiksha', 'State school infrastructure plan']),
    'Transport': ('Accessible bus stop and dependable last-mile service', ['State transport plan', 'Local-body access infrastructure']),
    'Housing': ('Weatherproof homes with water, sanitation and safe access', ['PMAY-G / PMAY-U subject to eligibility', 'State housing and local-body services']),
    'Digital Connectivity': ('Broadband service hub with resilient power', ['BharatNet subject to eligibility', 'State digital services plan']),
    'Other': ('Accessible community service and climate-resilience infrastructure', ['State disaster-mitigation plan where eligible', 'Local-body infrastructure budget']),
}

JURY_CASES = [
    {'key': 'karur_water', 'district': 'Karur', 'state': 'Tamil Nadu', 'category': 'Water Supply', 'ward': 12, 'status': 'Prioritized', 'urgency': 'Urgent', 'language': 'ta', 'title': 'Many voices, one water project', 'lesson': 'Aggregate recurring water requests, examine deprivation and water coverage, then propose storage, source protection and distribution as one project.'},
    {'key': 'chennai_drainage', 'district': 'Chennai', 'state': 'Tamil Nadu', 'category': 'Sanitation', 'ward': 8, 'status': 'In Progress', 'urgency': 'Routine', 'language': 'ta', 'title': 'Follow public works through execution', 'lesson': 'Show how drainage and road reinstatement can be coordinated, with dated officer remarks and an execution deadline.'},
    {'key': 'alluri_health', 'district': 'Alluri Sitharama Raju', 'state': 'Andhra Pradesh', 'category': 'Health', 'ward': 4, 'status': 'Capex Allocated', 'urgency': 'Routine', 'language': 'te', 'title': 'Rural need beyond the loudest hotspot', 'lesson': 'Compare lower report volumes with deprivation, access gaps and the population served. Explain why volume alone should not decide funding.'},
    {'key': 'visakhapatnam_safety', 'district': 'Visakhapatnam', 'state': 'Andhra Pradesh', 'category': 'Electricity', 'ward': 9, 'status': 'Escalated', 'urgency': 'Emergency', 'language': 'te', 'title': 'Separate immediate safety from capital planning', 'lesson': 'Escalate an immediate electrical hazard. Restore safety first; assess resilient feeder upgrades as a separate longer-term response.'},
    {'key': 'nalgonda_water', 'district': 'Nalgonda', 'state': 'Telangana', 'category': 'Water Supply', 'ward': 7, 'status': 'Closed', 'urgency': 'Routine', 'language': 'te', 'title': 'Check whether demand falls after delivery', 'lesson': 'Use the synthetic before/after cohort to explain impact monitoring. A decline is a demo signal; causal attribution also needs comparable controls and verified field evidence.'},
    {'key': 'hyderabad_digital', 'district': 'Hyderabad', 'state': 'Telangana', 'category': 'Digital Connectivity', 'ward': 10, 'status': 'Acknowledged', 'urgency': 'Routine', 'language': 'en', 'title': 'Digital infrastructure enables public services', 'lesson': 'Connect unreliable access at a service centre to a broadband and backup-power proposal, with a citizen-visible acknowledgement.'},
    {'key': 'tirupati_transport', 'district': 'Tirupati', 'state': 'Andhra Pradesh', 'category': 'Transport', 'ward': 6, 'status': 'Pending', 'urgency': 'Routine', 'language': 'te', 'title': 'Start with an incoming citizen request', 'lesson': 'Show the original Telugu text, its English translation and a consistent ticket ID before moving the request through officer review.'},
]
